# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        make release-docker-build GOARCH=amd64 GOOS=linux
        ls

    # - name: Action Template
    #   uses: release-engineers/action-template@v2
    #   with:
    #     # Source file relative to the working directory, a Jinja2 template
    #     source: 
    #     # Target file relative to the working directory, to either create or overwrite
    #     target: 
